# Generated by Django 6.0 on 2025-12-10 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='teacher_certificate')),
                ('is_active_for_booking', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('instruments', models.ManyToManyField(related_name='teacher_profile', to='instruments_app.instrument')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
