# Generated by Django 6.0 on 2025-12-22 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0001_initial'),
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='students_app.studentprofile'),
        ),
    ]
