# Generated by Django 6.0 on 2025-12-12 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries_app', '0001_initial'),
        ('students_app', '0001_initial'),
        ('teachers_app', '0002_alter_teacherprofile_default_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagethread',
            name='participants',
        ),
        migrations.AddField(
            model_name='messagethread',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='students_app.studentprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagethread',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='teachers_app.teacherprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='inquiry',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='inquiries_app.inquiry'),
            preserve_default=False,
        ),
    ]
